/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icons\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-font-messenger' : '&#x21;',
			'icon-font-help-circle' : '&#x22;',
			'icon-font-id' : '&#x23;',
			'icon-font-stamp' : '&#x24;',
			'icon-font-trash' : '&#x25;',
			'icon-font-printer' : '&#x26;',
			'icon-font-more' : '&#x27;',
			'icon-font-add' : '&#x28;',
			'icon-font-wrench' : '&#x29;',
			'icon-font-benchmarking' : '&#x2a;',
			'icon-font-layers-alt' : '&#x2b;',
			'icon-font-lines' : '&#x2c;',
			'icon-font-grid' : '&#x2d;',
			'icon-font-trash-ring' : '&#x2e;',
			'icon-font-id-ring' : '&#x2f;',
			'icon-font-stamp-ring' : '&#x30;',
			'icon-font-messenger-ring' : '&#x31;',
			'icon-font-benchmarking-ring' : '&#x32;',
			'icon-font-award-fill' : '&#x33;',
			'icon-font-winsows' : '&#x34;',
			'icon-font-envelope' : '&#x35;',
			'icon-font-printer-ring' : '&#x36;',
			'icon-font-synergylogo' : '&#x37;',
			'icon-font-wrench-ring' : '&#x38;',
			'icon-font-more-ring' : '&#x39;',
			'icon-font-add-ring' : '&#x3a;',
			'icon-font-home' : '&#x3b;',
			'icon-font-images' : '&#x3c;',
			'icon-font-camera' : '&#x3d;',
			'icon-font-support' : '&#x3e;',
			'icon-font-coin' : '&#x3f;',
			'icon-font-cart' : '&#x40;',
			'icon-font-phone' : '&#x41;',
			'icon-font-location' : '&#x42;',
			'icon-font-map' : '&#x43;',
			'icon-font-folder-open' : '&#x44;',
			'icon-font-stack' : '&#x45;',
			'icon-font-download' : '&#x46;',
			'icon-font-user' : '&#x47;',
			'icon-font-users' : '&#x48;',
			'icon-font-mobile' : '&#x49;',
			'icon-font-laptop' : '&#x4a;',
			'icon-font-mobile-2' : '&#x4b;',
			'icon-font-screen' : '&#x4c;',
			'icon-font-calendar' : '&#x4d;',
			'icon-font-clock' : '&#x4e;',
			'icon-font-bubbles' : '&#x4f;',
			'icon-font-user-2' : '&#x50;',
			'icon-font-cogs' : '&#x51;',
			'icon-font-cog' : '&#x52;',
			'icon-font-equalizer' : '&#x53;',
			'icon-font-wrench-2' : '&#x54;',
			'icon-font-key' : '&#x55;',
			'icon-font-search' : '&#x56;',
			'icon-font-cloud' : '&#x57;',
			'icon-font-menu' : '&#x58;',
			'icon-font-office' : '&#x59;',
			'icon-font-earth' : '&#x5a;',
			'icon-font-flag' : '&#x5b;',
			'icon-font-star' : '&#x5c;',
			'icon-font-star-2' : '&#x5d;',
			'icon-font-info' : '&#x5e;',
			'icon-font-question' : '&#x5f;',
			'icon-font-notification' : '&#x60;',
			'icon-font-table' : '&#x61;',
			'icon-font-filter' : '&#x62;',
			'icon-font-code' : '&#x63;',
			'icon-font-share' : '&#x64;',
			'icon-font-google' : '&#x65;',
			'icon-font-google-drive' : '&#x66;',
			'icon-font-facebook' : '&#x67;',
			'icon-font-twitter' : '&#x68;',
			'icon-font-tumblr' : '&#x69;',
			'icon-font-yahoo' : '&#x6a;',
			'icon-font-apple' : '&#x6b;',
			'icon-font-android' : '&#x6c;',
			'icon-font-windows' : '&#x6d;',
			'icon-font-windows8' : '&#x6e;',
			'icon-font-skype' : '&#x6f;',
			'icon-font-linkedin' : '&#x70;',
			'icon-font-paypal' : '&#x71;',
			'icon-font-file-pdf' : '&#x72;',
			'icon-font-file-word' : '&#x73;',
			'icon-font-file-excel' : '&#x74;',
			'icon-font-file-powerpoint' : '&#x75;',
			'icon-font-file-zip' : '&#x76;',
			'icon-font-file-xml' : '&#x77;',
			'icon-font-file-css' : '&#x78;',
			'icon-font-file-openoffice' : '&#x79;',
			'icon-font-html5' : '&#x7a;',
			'icon-font-html5-2' : '&#x7b;',
			'icon-font-css3' : '&#x7c;',
			'icon-font-chrome' : '&#x7d;',
			'icon-font-firefox' : '&#x7e;',
			'icon-font-IE' : '&#xe000;',
			'icon-font-opera' : '&#xe001;',
			'icon-font-safari' : '&#xe002;',
			'icon-font-newspaper' : '&#xe003;',
			'icon-font-books' : '&#xe004;',
			'icon-font-credit' : '&#xe005;',
			'icon-font-calendar-2' : '&#xe006;',
			'icon-font-shield' : '&#xe007;',
			'icon-font-pushpin' : '&#xe008;',
			'icon-font-pencil-ring' : '&#xe009;',
			'icon-font-pencil' : '&#xe00a;',
			'icon-font-flipvertical-ring' : '&#xe00b;',
			'icon-font-flipvertical' : '&#xe00c;',
			'icon-font-filter-ring' : '&#xe00d;',
			'icon-font-filter-2' : '&#xe00e;',
			'icon-font-diskette-ring' : '&#xe00f;',
			'icon-font-diskette' : '&#xe010;',
			'icon-font-calendar2-ring' : '&#xe011;',
			'icon-font-calendar2' : '&#xe012;',
			'icon-font-arrowright2-ring' : '&#xe013;',
			'icon-font-arrowright2' : '&#xe014;',
			'icon-font-arrowleft2-ring' : '&#xe015;',
			'icon-font-arrowleft2' : '&#xe016;',
			'icon-font-meter' : '&#xe017;',
			'icon-font-stats' : '&#xe018;',
			'icon-font-bars' : '&#xe019;',
			'icon-font-pie' : '&#xe01a;',
			'icon-font-curved-arrow' : '&#xe01b;',
			'icon-font-close' : '&#xe01c;',
			'icon-font-exit' : '&#xe01d;',
			'icon-font-chevron-up' : '&#xe01e;',
			'icon-font-chevron-down' : '&#xe01f;',
			'icon-font-refresh' : '&#xe020;',
			'icon-font-arrow-up' : '&#xe021;',
			'icon-font-arrow-down' : '&#xe022;',
			'icon-font-link' : '&#xe023;',
			'icon-font-resize-full' : '&#xe024;',
			'icon-font-resize-small' : '&#xe025;',
			'icon-font-edit' : '&#xe026;',
			'icon-font-sort' : '&#xe027;',
			'icon-font-ok' : '&#xe028;',
			'icon-font-ban-circle' : '&#xe029;',
			'icon-font-upload' : '&#xe02a;',
			'icon-font-spinner' : '&#xe02b;',
			'icon-font-lock' : '&#xe02c;',
			'icon-font-unlocked' : '&#xe02d;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-font-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};